[package]
name = "seph-daemon"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
directories = "5.0.1"
libseph = { path = "../lib" }
signal-hook = "0.3.16"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
